using FleetManager.EntityFrameworkDAL.Models.Entities;
using Microsoft.EntityFrameworkCore;
using FleetManager.EntityFrameworkDAL.Models.Enums; 

namespace FleetManager.EntityFrameworkDAL.Context.Seeding.TestSeeding;
public static class InquiryTypeTestSeed {
    public static void TestSeedInquiryType(this ModelBuilder modelBuilder) {
        modelBuilder.Entity<InquiryType>().HasData(
            new InquiryType { ID = 1,  Name = "General Inquiry",                        Category = InquiryCategory.General, AppointmentNeeded = false },
            new InquiryType { ID = 2,  Name = "Feedback",                               Category = InquiryCategory.General, AppointmentNeeded = false },
            new InquiryType { ID = 3,  Name = "Complaint",                              Category = InquiryCategory.General, AppointmentNeeded = false },
            new InquiryType { ID = 4,  Name = "Information Request",                    Category = InquiryCategory.General, AppointmentNeeded = false },
            new InquiryType { ID = 5,  Name = "Service Inquiry",                        Category = InquiryCategory.General, AppointmentNeeded = true },
            new InquiryType { ID = 6,  Name = "Billing Inquiry",                        Category = InquiryCategory.General, AppointmentNeeded = false },
            new InquiryType { ID = 7,  Name = "Technical Support",                      Category = InquiryCategory.General, AppointmentNeeded = true },
            new InquiryType { ID = 8,  Name = "Product Inquiry",                        Category = InquiryCategory.General, AppointmentNeeded = false },
            new InquiryType { ID = 9,  Name = "Suggestion",                             Category = InquiryCategory.General, AppointmentNeeded = false },
            new InquiryType { ID = 10, Name = "Request for Assistance",                 Category = InquiryCategory.General, AppointmentNeeded = true },
            new InquiryType { ID = 11, Name = "Lost and Found",                         Category = InquiryCategory.General, AppointmentNeeded = false },
            new InquiryType { ID = 12, Name = "Change of Contact Information",          Category = InquiryCategory.General, AppointmentNeeded = false },
            new InquiryType { ID = 13, Name = "Privacy Concern",                        Category = InquiryCategory.General, AppointmentNeeded = false },
            new InquiryType { ID = 14, Name = "Report a Bug",                           Category = InquiryCategory.General, AppointmentNeeded = false },
            new InquiryType { ID = 15, Name = "Account Closure",                        Category = InquiryCategory.General, AppointmentNeeded = true },
            new InquiryType { ID = 16, Name = "Request for Brochure",                   Category = InquiryCategory.General, AppointmentNeeded = false },
            new InquiryType { ID = 17, Name = "Refund Request",                         Category = InquiryCategory.General, AppointmentNeeded = false },
            new InquiryType { ID = 18, Name = "Cancellation Request",                   Category = InquiryCategory.General, AppointmentNeeded = true },
            new InquiryType { ID = 19, Name = "Delivery Inquiry",                       Category = InquiryCategory.General, AppointmentNeeded = false },
            new InquiryType { ID = 20, Name = "Account Activation",                     Category = InquiryCategory.General, AppointmentNeeded = false },
            new InquiryType { ID = 21, Name = "Event Participation Inquiry",            Category = InquiryCategory.General, AppointmentNeeded = false },
            new InquiryType { ID = 22, Name = "Discount Inquiry",                       Category = InquiryCategory.General, AppointmentNeeded = false },
            new InquiryType { ID = 23, Name = "Membership Inquiry",                     Category = InquiryCategory.General, AppointmentNeeded = false },
            new InquiryType { ID = 24, Name = "Request for User Manual",                Category = InquiryCategory.General, AppointmentNeeded = false },
            new InquiryType { ID = 25, Name = "Website Feedback",                       Category = InquiryCategory.General, AppointmentNeeded = false },
            new InquiryType { ID = 26, Name = "Emergency Assistance",                   Category = InquiryCategory.General, AppointmentNeeded = true },
            new InquiryType { ID = 27, Name = "Request for Presentation",               Category = InquiryCategory.General, AppointmentNeeded = true },
            new InquiryType { ID = 28, Name = "Lost Item Inquiry",                      Category = InquiryCategory.General, AppointmentNeeded = false },
            new InquiryType { ID = 29, Name = "Change of Delivery Address",             Category = InquiryCategory.General, AppointmentNeeded = false },
            new InquiryType { ID = 30, Name = "Request for Test Drive",                 Category = InquiryCategory.General, AppointmentNeeded = true },

            new InquiryType { ID = 31, Name = "Account Registration",                   Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 32, Name = "Password Reset",                         Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 33, Name = "Login Assistance",                       Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 34, Name = "Profile Update",                         Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 35, Name = "Subscription Management",                Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 36, Name = "Account Closure",                        Category = InquiryCategory.User, AppointmentNeeded = true },
            new InquiryType { ID = 37, Name = "Feedback",                               Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 38, Name = "Change of Contact Information",          Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 39, Name = "Request for User Manual",                Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 40, Name = "Privacy Concern",                        Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 41, Name = "Account Activation",                     Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 42, Name = "Change of Email Address",                Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 43, Name = "Feedback on User Experience",            Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 44, Name = "Subscription Renewal",                   Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 45, Name = "Membership Inquiry",                     Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 46, Name = "Profile Photo Update",                   Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 47, Name = "Account Security",                       Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 48, Name = "User Authentication Issue",              Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 49, Name = "Request for Training",                   Category = InquiryCategory.User, AppointmentNeeded = true },
            new InquiryType { ID = 50, Name = "Account Termination Request",            Category = InquiryCategory.User, AppointmentNeeded = true },
            new InquiryType { ID = 51, Name = "Deactivation of Account",                Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 52, Name = "Account Recovery",                       Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 53, Name = "Account Lockout",                        Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 54, Name = "Social Media Linking",                   Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 55, Name = "User Data Access",                       Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 56, Name = "Feedback on Account Management",         Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 57, Name = "User Privacy",                           Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 58, Name = "Account Merge Request",                  Category = InquiryCategory.User, AppointmentNeeded = true },
            new InquiryType { ID = 59, Name = "Preferred Communication Method",         Category = InquiryCategory.User, AppointmentNeeded = false },
            new InquiryType { ID = 60, Name = "User Experience Enhancement",            Category = InquiryCategory.User, AppointmentNeeded = false },

            new InquiryType { ID = 61, Name = "Fuel Card Activation",                   Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 62, Name = "Fuel Card Application",                  Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 63, Name = "Lost Fuel Card",                         Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 64, Name = "Fuel Card PIN Reset",                    Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 65, Name = "Fuel Card Renewal",                      Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 66, Name = "Fuel Card Cancellation",                 Category = InquiryCategory.FuelCard, AppointmentNeeded = true },
            new InquiryType { ID = 67, Name = "Fuel Card Usage Inquiry",                Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 68, Name = "Fuel Card Billing Inquiry",              Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 69, Name = "Fuel Card Payment Issue",                Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 70, Name = "Fuel Card Statement Request",            Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 71, Name = "Fuel Card Transaction Dispute",          Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 72, Name = "Fuel Card Usage Limit Adjustment",       Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 73, Name = "Fuel Card PIN Change",                   Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 74, Name = "Fuel Card Account Update",               Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 75, Name = "Fuel Card Network Coverage Inquiry",     Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 76, Name = "Fuel Card Benefits Inquiry",             Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 77, Name = "Fuel Card Security Concern",             Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 78, Name = "Fuel Card Replacement",                  Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 79, Name = "Fuel Card PIN Unlock",                   Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 80, Name = "Fuel Card Balance Inquiry",              Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 81, Name = "Fuel Card Expiry Date Update",           Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 82, Name = "Fuel Card Transaction History",          Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 83, Name = "Fuel Card Account Closure",              Category = InquiryCategory.FuelCard, AppointmentNeeded = true },
            new InquiryType { ID = 84, Name = "Fuel Card PIN Reissue",                  Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 85, Name = "Fuel Card Enrollment",                   Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 86, Name = "Fuel Card Discount Offers",              Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 87, Name = "Fuel Card Fraud Alert",                  Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 88, Name = "Fuel Card Mobile App Support",           Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 89, Name = "Fuel Card PIN Security",                 Category = InquiryCategory.FuelCard, AppointmentNeeded = false },
            new InquiryType { ID = 90, Name = "Fuel Card Usage Tips",                   Category = InquiryCategory.FuelCard, AppointmentNeeded = false },

            new InquiryType { ID = 91, Name = "Vehicle Purchase Inquiry",               Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 92, Name = "Vehicle Service Appointment",            Category = InquiryCategory.Vehicle, AppointmentNeeded = true },
            new InquiryType { ID = 93, Name = "Vehicle Test Drive Request",             Category = InquiryCategory.Vehicle, AppointmentNeeded = true },
            new InquiryType { ID = 94, Name = "Vehicle Lease Inquiry",                  Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 95, Name = "Vehicle Model Availability",             Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 96, Name = "Vehicle Configuration Assistance",       Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 97, Name = "Vehicle Trade-In Valuation",             Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 98, Name = "Vehicle Financing Options",              Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 99, Name = "Vehicle Warranty Information",           Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 100, Name = "Vehicle Fuel Efficiency Inquiry",       Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 101, Name = "Vehicle Maintenance Schedule",          Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 102, Name = "Vehicle Recall Information",            Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 103, Name = "Vehicle Safety Features",               Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 104, Name = "Vehicle Exterior Options",              Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 105, Name = "Vehicle Interior Features",             Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 106, Name = "Vehicle Technology Inquiry",            Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 107, Name = "Vehicle Color Options",                 Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 108, Name = "Vehicle Availability Inquiry",          Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 109, Name = "Vehicle Rental Inquiry",                Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 110, Name = "Vehicle Trade-In Process",              Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 111, Name = "Vehicle Customization Inquiry",         Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 112, Name = "Vehicle Performance Specifications",    Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 113, Name = "Vehicle Price Negotiation",             Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 114, Name = "Vehicle Delivery Process",              Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 115, Name = "Vehicle Insurance Options",             Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 116, Name = "Vehicle Resale Value Inquiry",          Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 117, Name = "Vehicle Ownership Costs",               Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 118, Name = "Vehicle Financing Approval",            Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 119, Name = "Vehicle Trade-In Assessment",           Category = InquiryCategory.Vehicle, AppointmentNeeded = false },
            new InquiryType { ID = 120, Name = "Vehicle Mileage Estimate",              Category = InquiryCategory.Vehicle, AppointmentNeeded = false }

        );
    }
}