using FleetManager.EntityFrameworkDAL.Models.Entities;
using Microsoft.EntityFrameworkCore;

namespace FleetManager.EntityFrameworkDAL.Context.Seeding.TestSeeding;
public static class MaintenanceTaskTestSeed {
    public static void TestSeedMaintenanceTask(this ModelBuilder modelBuilder) {
        modelBuilder.Entity<MaintenanceTask>().HasData(
            new MaintenanceTask() { ID = 1, MaintenanceID = 6, Description = "Replaced the tires with summer tires." },
            new MaintenanceTask() { ID = 2, MaintenanceID = 2, Description = "Performed oil change and filter replacement." },
            new MaintenanceTask() { ID = 3, MaintenanceID = 45, Description = "Inspected and adjusted the brake system." },
            new MaintenanceTask() { ID = 4, MaintenanceID = 18, Description = "Repaired the exhaust system." },
            new MaintenanceTask() { ID = 5, MaintenanceID = 34, Description = "Replaced the windshield wipers." },
            new MaintenanceTask() { ID = 6, MaintenanceID = 76, Description = "Performed coolant flush and refill." },
            new MaintenanceTask() { ID = 7, MaintenanceID = 89, Description = "Inspected and replaced spark plugs." },
            new MaintenanceTask() { ID = 8, MaintenanceID = 55, Description = "Checked and adjusted the wheel alignment." },
            new MaintenanceTask() { ID = 9, MaintenanceID = 12, Description = "Recharged the air conditioning system." },
            new MaintenanceTask() { ID = 10, MaintenanceID = 67, Description = "Performed battery test and replaced if necessary." },
            new MaintenanceTask() { ID = 11, MaintenanceID = 91, Description = "Inspected and replaced the serpentine belt." },
            new MaintenanceTask() { ID = 12, MaintenanceID = 25, Description = "Performed transmission fluid change." },
            new MaintenanceTask() { ID = 13, MaintenanceID = 63, Description = "Checked and adjusted tire pressure." },
            new MaintenanceTask() { ID = 14, MaintenanceID = 40, Description = "Replaced the cabin air filter." },
            new MaintenanceTask() { ID = 15, MaintenanceID = 83, Description = "Performed brake fluid flush and refill." },
            new MaintenanceTask() { ID = 16, MaintenanceID = 7, Description = "Checked and replaced the engine air filter." },
            new MaintenanceTask() { ID = 17, MaintenanceID = 30, Description = "Inspected and replaced worn suspension components." },
            new MaintenanceTask() { ID = 18, MaintenanceID = 95, Description = "Performed engine diagnostics and troubleshooting." },
            new MaintenanceTask() { ID = 19, MaintenanceID = 52, Description = "Replaced the fuel filter." },
            new MaintenanceTask() { ID = 20, MaintenanceID = 37, Description = "Checked and replaced worn drive belts." },
            new MaintenanceTask() { ID = 21, MaintenanceID = 72, Description = "Performed power steering fluid flush and refill." },
            new MaintenanceTask() { ID = 22, MaintenanceID = 99, Description = "Inspected and replaced worn brake pads." },
            new MaintenanceTask() { ID = 23, MaintenanceID = 14, Description = "Replaced the battery." },
            new MaintenanceTask() { ID = 24, MaintenanceID = 79, Description = "Performed fuel system cleaning and injector service." },
            new MaintenanceTask() { ID = 25, MaintenanceID = 48, Description = "Checked and replaced the timing belt." },
            new MaintenanceTask() { ID = 26, MaintenanceID = 61, Description = "Replaced the alternator." },
            new MaintenanceTask() { ID = 27, MaintenanceID = 9, Description = "Inspected and replaced worn CV joints." },
            new MaintenanceTask() { ID = 28, MaintenanceID = 42, Description = "Performed coolant system pressure test." },
            new MaintenanceTask() { ID = 29, MaintenanceID = 86, Description = "Checked and replaced worn ignition coils." },
            new MaintenanceTask() { ID = 30, MaintenanceID = 19, Description = "Replaced the radiator." },
            new MaintenanceTask() { ID = 31, MaintenanceID = 70, Description = "Performed suspension alignment." },
            new MaintenanceTask() { ID = 32, MaintenanceID = 93, Description = "Inspected and replaced worn wheel bearings." },
            new MaintenanceTask() { ID = 33, MaintenanceID = 16, Description = "Repaired the power window mechanism." },
            new MaintenanceTask() { ID = 34, MaintenanceID = 82, Description = "Performed emissions system check." },
            new MaintenanceTask() { ID = 35, MaintenanceID = 57, Description = "Checked and replaced the thermostat." },
            new MaintenanceTask() { ID = 36, MaintenanceID = 32, Description = "Replaced the oxygen sensor." },
            new MaintenanceTask() { ID = 37, MaintenanceID = 74, Description = "Inspected and replaced worn tie rod ends." },
            new MaintenanceTask() { ID = 38, MaintenanceID = 97, Description = "Performed electrical system check." },
            new MaintenanceTask() { ID = 39, MaintenanceID = 23, Description = "Checked and replaced worn sway bar links." },
            new MaintenanceTask() { ID = 40, MaintenanceID = 64, Description = "Repaired the power door lock system." },
            new MaintenanceTask() { ID = 41, MaintenanceID = 44, Description = "Performed fuel pressure test." },
            new MaintenanceTask() { ID = 42, MaintenanceID = 88, Description = "Checked and replaced the camshaft position sensor." },
            new MaintenanceTask() { ID = 43, MaintenanceID = 10, Description = "Repaired the starter motor." },
            new MaintenanceTask() { ID = 44, MaintenanceID = 50, Description = "Inspected and replaced worn control arm bushings." },
            new MaintenanceTask() { ID = 45, MaintenanceID = 35, Description = "Performed engine tune-up." },
            new MaintenanceTask() { ID = 46, MaintenanceID = 77, Description = "Replaced the water pump." },
            new MaintenanceTask() { ID = 47, MaintenanceID = 92, Description = "Inspected and replaced worn brake rotors." },
            new MaintenanceTask() { ID = 48, MaintenanceID = 13, Description = "Checked and replaced the mass airflow sensor." },
            new MaintenanceTask() { ID = 49, MaintenanceID = 81, Description = "Repaired the power steering pump." },
            new MaintenanceTask() { ID = 50, MaintenanceID = 26, Description = "Performed fuel injector cleaning." },
            new MaintenanceTask() { ID = 51, MaintenanceID = 68, Description = "Checked and replaced worn ball joints." },
            new MaintenanceTask() { ID = 52, MaintenanceID = 3, Description = "Repaired the power steering hose." },
            new MaintenanceTask() { ID = 53, MaintenanceID = 66, Description = "Inspected and replaced worn shock absorbers." },
            new MaintenanceTask() { ID = 54, MaintenanceID = 20, Description = "Performed fuel system pressure test." },
            new MaintenanceTask() { ID = 55, MaintenanceID = 85, Description = "Checked and replaced the throttle position sensor." },
            new MaintenanceTask() { ID = 56, MaintenanceID = 21, Description = "Replaced the ignition switch." },
            new MaintenanceTask() { ID = 57, MaintenanceID = 71, Description = "Inspected and replaced worn sway bar bushings." },
            new MaintenanceTask() { ID = 58, MaintenanceID = 94, Description = "Performed power window motor replacement." },
            new MaintenanceTask() { ID = 59, MaintenanceID = 17, Description = "Checked and replaced the crankshaft position sensor." },
            new MaintenanceTask() { ID = 60, MaintenanceID = 58, Description = "Repaired the fuel tank." },
            new MaintenanceTask() { ID = 61, MaintenanceID = 31, Description = "Inspected and replaced worn struts." },
            new MaintenanceTask() { ID = 62, MaintenanceID = 75, Description = "Performed engine vacuum leak test." },
            new MaintenanceTask() { ID = 63, MaintenanceID = 96, Description = "Checked and replaced the knock sensor." },
            new MaintenanceTask() { ID = 64, MaintenanceID = 24, Description = "Repaired the power seat mechanism." },
            new MaintenanceTask() { ID = 65, MaintenanceID = 65, Description = "Inspected and replaced worn control arm joints." },
            new MaintenanceTask() { ID = 66, MaintenanceID = 41, Description = "Performed cooling system pressure test." },
            new MaintenanceTask() { ID = 67, MaintenanceID = 87, Description = "Checked and replaced the fuel pressure regulator." },
            new MaintenanceTask() { ID = 68, MaintenanceID = 11, Description = "Repaired the alternator belt." },
            new MaintenanceTask() { ID = 69, MaintenanceID = 49, Description = "Inspected and replaced worn CV boots." },
            new MaintenanceTask() { ID = 70, MaintenanceID = 36, Description = "Performed throttle body cleaning." },
            new MaintenanceTask() { ID = 71, MaintenanceID = 78, Description = "Checked and replaced the fuel pump." },
            new MaintenanceTask() { ID = 72, MaintenanceID = 90, Description = "Repaired the power mirror." },
            new MaintenanceTask() { ID = 73, MaintenanceID = 15, Description = "Inspected and replaced worn bushings." },
            new MaintenanceTask() { ID = 74, MaintenanceID = 80, Description = "Performed ignition system check." },
            new MaintenanceTask() { ID = 75, MaintenanceID = 29, Description = "Checked and replaced the fuel cap." },
            new MaintenanceTask() { ID = 76, MaintenanceID = 62, Description = "Replaced the AC compressor." },
            new MaintenanceTask() { ID = 77, MaintenanceID = 43, Description = "Inspected and replaced worn control arm brackets." },
            new MaintenanceTask() { ID = 78, MaintenanceID = 89, Description = "Performed battery voltage test." },
            new MaintenanceTask() { ID = 79, MaintenanceID = 9, Description = "Repaired the power steering rack." },
            new MaintenanceTask() { ID = 80, MaintenanceID = 48, Description = "Checked and replaced the fuel filter." },
            new MaintenanceTask() { ID = 81, MaintenanceID = 33, Description = "Inspected and replaced worn stabilizer bar links." },
            new MaintenanceTask() { ID = 82, MaintenanceID = 76, Description = "Performed engine compression test." },
            new MaintenanceTask() { ID = 83, MaintenanceID = 98, Description = "Checked and replaced the fuel injectors." },
            new MaintenanceTask() { ID = 84, MaintenanceID = 22, Description = "Repaired the power trunk release." },
            new MaintenanceTask() { ID = 85, MaintenanceID = 67, Description = "Inspected and replaced worn strut mounts." },
            new MaintenanceTask() { ID = 86, MaintenanceID = 40, Description = "Performed radiator flush and coolant replacement." },
            new MaintenanceTask() { ID = 87, MaintenanceID = 93, Description = "Checked and replaced the fuel level sensor." },
            new MaintenanceTask() { ID = 88, MaintenanceID = 8, Description = "Repaired the power window switch." },
            new MaintenanceTask() { ID = 89, MaintenanceID = 55, Description = "Inspected and replaced worn bushing brackets." },
            new MaintenanceTask() { ID = 90, MaintenanceID = 34, Description = "Performed throttle position sensor calibration." },
            new MaintenanceTask() { ID = 91, MaintenanceID = 79, Description = "Checked and replaced the fuel tank cap." },
            new MaintenanceTask() { ID = 92, MaintenanceID = 91, Description = "Repaired the power antenna." },
            new MaintenanceTask() { ID = 93, MaintenanceID = 14, Description = "Inspected and replaced worn steering gear." },
            new MaintenanceTask() { ID = 94, MaintenanceID = 73, Description = "Performed engine oil pressure test." },
            new MaintenanceTask() { ID = 95, MaintenanceID = 95, Description = "Checked and replaced the fuel pressure sensor." },
            new MaintenanceTask() { ID = 96, MaintenanceID = 25, Description = "Repaired the power sunroof mechanism." },
            new MaintenanceTask() { ID = 97, MaintenanceID = 64, Description = "Inspected and replaced worn sway bar end links." },
            new MaintenanceTask() { ID = 98, MaintenanceID = 45, Description = "Performed throttle body replacement." },
            new MaintenanceTask() { ID = 99, MaintenanceID = 99, Description = "Checked and replaced the fuel pump relay." },
            new MaintenanceTask() { ID = 100, MaintenanceID = 28, Description = "Replaced the AC condenser." },
            new MaintenanceTask() { ID = 101, MaintenanceID = 14, Description = "Performed brake fluid flush and replacement." },
            new MaintenanceTask() { ID = 102, MaintenanceID = 53, Description = "Checked and replaced the transmission fluid filter." },
            new MaintenanceTask() { ID = 103, MaintenanceID = 24, Description = "Repaired the power steering pump." },
            new MaintenanceTask() { ID = 104, MaintenanceID = 86, Description = "Inspected and replaced worn wheel bearings." },
            new MaintenanceTask() { ID = 105, MaintenanceID = 41, Description = "Performed transmission fluid flush and replacement." },
            new MaintenanceTask() { ID = 106, MaintenanceID = 25, Description = "Replaced the power steering pressure hose." },
            new MaintenanceTask() { ID = 107, MaintenanceID = 67, Description = "Checked and replaced the differential fluid." },
            new MaintenanceTask() { ID = 108, MaintenanceID = 58, Description = "Inspected and replaced worn axle seals." },
            new MaintenanceTask() { ID = 109, MaintenanceID = 31, Description = "Performed engine coolant flush and replacement." },
            new MaintenanceTask() { ID = 110, MaintenanceID = 73, Description = "Repaired the power steering gear." },
            new MaintenanceTask() { ID = 111, MaintenanceID = 49, Description = "Checked and replaced the transfer case fluid." },
            new MaintenanceTask() { ID = 112, MaintenanceID = 92, Description = "Inspected and replaced worn CV joints." },
            new MaintenanceTask() { ID = 113, MaintenanceID = 36, Description = "Performed differential fluid flush and replacement." },
            new MaintenanceTask() { ID = 114, MaintenanceID = 34, Description = "Replaced the power steering reservoir." },
            new MaintenanceTask() { ID = 115, MaintenanceID = 78, Description = "Checked and replaced the brake pads." },
            new MaintenanceTask() { ID = 116, MaintenanceID = 45, Description = "Inspected and replaced worn wheel studs." },
            new MaintenanceTask() { ID = 117, MaintenanceID = 97, Description = "Performed power steering fluid flush and replacement." },
            new MaintenanceTask() { ID = 118, MaintenanceID = 82, Description = "Repaired the differential." },
            new MaintenanceTask() { ID = 119, MaintenanceID = 56, Description = "Checked and replaced the transmission mount." },
            new MaintenanceTask() { ID = 120, MaintenanceID = 23, Description = "Inspected and replaced worn U-joints." },
            new MaintenanceTask() { ID = 121, MaintenanceID = 70, Description = "Performed brake caliper rebuild." },
            new MaintenanceTask() { ID = 122, MaintenanceID = 37, Description = "Replaced the power steering belt." },
            new MaintenanceTask() { ID = 123, MaintenanceID = 65, Description = "Checked and replaced the differential gasket." },
            new MaintenanceTask() { ID = 124, MaintenanceID = 76, Description = "Inspected and replaced worn brake rotors." },
            new MaintenanceTask() { ID = 125, MaintenanceID = 30, Description = "Performed axle fluid flush and replacement." },
            new MaintenanceTask() { ID = 126, MaintenanceID = 91, Description = "Repaired the power steering control valve." },
            new MaintenanceTask() { ID = 127, MaintenanceID = 80, Description = "Checked and replaced the brake lines." },
            new MaintenanceTask() { ID = 128, MaintenanceID = 47, Description = "Inspected and replaced worn brake calipers." },
            new MaintenanceTask() { ID = 129, MaintenanceID = 95, Description = "Performed transmission cooler replacement." },
            new MaintenanceTask() { ID = 130, MaintenanceID = 26, Description = "Replaced the power steering pulley." },
            new MaintenanceTask() { ID = 131, MaintenanceID = 75, Description = "Checked and replaced the differential pinion seal." },
            new MaintenanceTask() { ID = 132, MaintenanceID = 46, Description = "Inspected and replaced worn brake hoses." },
            new MaintenanceTask() { ID = 133, MaintenanceID = 12, Description = "Performed engine mount replacement." },
            new MaintenanceTask() { ID = 134, MaintenanceID = 89, Description = "Repaired the power steering fluid cooler." },
            new MaintenanceTask() { ID = 135, MaintenanceID = 71, Description = "Checked and replaced the brake booster." },
            new MaintenanceTask() { ID = 136, MaintenanceID = 40, Description = "Inspected and replaced worn brake master cylinder." },
            new MaintenanceTask() { ID = 137, MaintenanceID = 72, Description = "Performed transmission mount replacement." },
            new MaintenanceTask() { ID = 138, MaintenanceID = 57, Description = "Replaced the power steering pressure switch." },
            new MaintenanceTask() { ID = 139, MaintenanceID = 16, Description = "Checked and replaced the engine oil pan." },
            new MaintenanceTask() { ID = 140, MaintenanceID = 59, Description = "Inspected and replaced worn engine mounts." },
            new MaintenanceTask() { ID = 141, MaintenanceID = 4, Description = "Performed transmission pan replacement." },
            new MaintenanceTask() { ID = 142, MaintenanceID = 93, Description = "Repaired the power steering return hose." },
            new MaintenanceTask() { ID = 143, MaintenanceID = 51, Description = "Checked and replaced the engine oil filter." },
            new MaintenanceTask() { ID = 144, MaintenanceID = 37, Description = "Inspected and replaced worn power steering lines." },
            new MaintenanceTask() { ID = 145, MaintenanceID = 20, Description = "Performed engine oil cooler replacement." },
            new MaintenanceTask() { ID = 146, MaintenanceID = 9, Description = "Replaced the power steering control module." },
            new MaintenanceTask() { ID = 147, MaintenanceID = 48, Description = "Checked and replaced the engine air filter." },
            new MaintenanceTask() { ID = 148, MaintenanceID = 39, Description = "Inspected and replaced worn engine belts." },
            new MaintenanceTask() { ID = 149, MaintenanceID = 3, Description = "Performed engine oil pump replacement." },
            new MaintenanceTask() { ID = 150, MaintenanceID = 32, Description = "Repaired the power steering reservoir cap." },
            new MaintenanceTask() { ID = 151, MaintenanceID = 69, Description = "Checked and replaced the engine coolant temperature sensor." },
            new MaintenanceTask() { ID = 152, MaintenanceID = 42, Description = "Inspected and replaced worn spark plugs." },
            new MaintenanceTask() { ID = 153, MaintenanceID = 33, Description = "Performed engine oil pressure switch replacement." },
            new MaintenanceTask() { ID = 154, MaintenanceID = 24, Description = "Replaced the power steering control arm." },
            new MaintenanceTask() { ID = 155, MaintenanceID = 63, Description = "Checked and replaced the engine crankshaft position sensor." },
            new MaintenanceTask() { ID = 156, MaintenanceID = 62, Description = "Inspected and replaced worn ignition coils." },
            new MaintenanceTask() { ID = 157, MaintenanceID = 27, Description = "Performed engine oil level sensor replacement." },
            new MaintenanceTask() { ID = 158, MaintenanceID = 54, Description = "Repaired the power steering gear box." },
            new MaintenanceTask() { ID = 159, MaintenanceID = 95, Description = "Checked and replaced the engine camshaft position sensor." },
            new MaintenanceTask() { ID = 160, MaintenanceID = 64, Description = "Inspected and replaced worn fuel injectors." },
            new MaintenanceTask() { ID = 161, MaintenanceID = 39, Description = "Performed engine oil filler cap replacement." },
            new MaintenanceTask() { ID = 162, MaintenanceID = 50, Description = "Replaced the power steering rack." },
            new MaintenanceTask() { ID = 163, MaintenanceID = 61, Description = "Checked and replaced the engine throttle position sensor." },
            new MaintenanceTask() { ID = 164, MaintenanceID = 73, Description = "Inspected and replaced worn fuel pump." },
            new MaintenanceTask() { ID = 165, MaintenanceID = 7, Description = "Performed engine oil drain plug replacement." },
            new MaintenanceTask() { ID = 166, MaintenanceID = 68, Description = "Repaired the power steering control module connector." },
            new MaintenanceTask() { ID = 167, MaintenanceID = 53, Description = "Checked and replaced the engine intake manifold." },
            new MaintenanceTask() { ID = 168, MaintenanceID = 84, Description = "Inspected and replaced worn oxygen sensor." },
            new MaintenanceTask() { ID = 169, MaintenanceID = 56, Description = "Performed engine oil cap replacement." },
            new MaintenanceTask() { ID = 170, MaintenanceID = 33, Description = "Replaced the power steering pump pulley." },
            new MaintenanceTask() { ID = 171, MaintenanceID = 49, Description = "Checked and replaced the engine exhaust manifold." },
            new MaintenanceTask() { ID = 172, MaintenanceID = 3, Description = "Inspected and replaced worn engine gaskets." },
            new MaintenanceTask() { ID = 173, MaintenanceID = 58, Description = "Performed engine oil cooler hose replacement." },
            new MaintenanceTask() { ID = 174, MaintenanceID = 44, Description = "Repaired the power steering pressure line." },
            new MaintenanceTask() { ID = 175, MaintenanceID = 65, Description = "Checked and replaced the engine timing chain." },
            new MaintenanceTask() { ID = 176, MaintenanceID = 2, Description = "Inspected and replaced worn engine sensors." },
            new MaintenanceTask() { ID = 177, MaintenanceID = 79, Description = "Performed engine oil pan gasket replacement." },
            new MaintenanceTask() { ID = 178, MaintenanceID = 24, Description = "Replaced the power steering control valve seal." },
            new MaintenanceTask() { ID = 179, MaintenanceID = 83, Description = "Checked and replaced the engine valve cover." },
            new MaintenanceTask() { ID = 180, MaintenanceID = 92, Description = "Inspected and replaced worn fuel filters." },
            new MaintenanceTask() { ID = 181, MaintenanceID = 37, Description = "Performed engine oil pressure relief valve replacement." },
            new MaintenanceTask() { ID = 182, MaintenanceID = 91, Description = "Repaired the power steering pressure regulator." },
            new MaintenanceTask() { ID = 183, MaintenanceID = 60, Description = "Checked and replaced the engine timing belt." },
            new MaintenanceTask() { ID = 184, MaintenanceID = 40, Description = "Inspected and replaced worn ignition wires." },
            new MaintenanceTask() { ID = 185, MaintenanceID = 25, Description = "Performed engine oil filter housing replacement." },
            new MaintenanceTask() { ID = 186, MaintenanceID = 62, Description = "Replaced the power steering reservoir cap." },
            new MaintenanceTask() { ID = 187, MaintenanceID = 76, Description = "Checked and replaced the engine valve seals." },
            new MaintenanceTask() { ID = 188, MaintenanceID = 14, Description = "Inspected and replaced worn fuel injectors seals." },
            new MaintenanceTask() { ID = 189, MaintenanceID = 63, Description = "Performed engine oil cooler gasket replacement." },
            new MaintenanceTask() { ID = 190, MaintenanceID = 82, Description = "Repaired the power steering pressure hose." },
            new MaintenanceTask() { ID = 191, MaintenanceID = 44, Description = "Checked and replaced the engine intake valve." },
            new MaintenanceTask() { ID = 192, MaintenanceID = 77, Description = "Inspected and replaced worn ignition coils." },
            new MaintenanceTask() { ID = 193, MaintenanceID = 52, Description = "Performed engine oil pump gasket replacement." },
            new MaintenanceTask() { ID = 194, MaintenanceID = 84, Description = "Replaced the power steering return line." },
            new MaintenanceTask() { ID = 195, MaintenanceID = 85, Description = "Checked and replaced the engine exhaust valve." },
            new MaintenanceTask() { ID = 196, MaintenanceID = 62, Description = "Inspected and replaced worn fuel pressure regulator." },
            new MaintenanceTask() { ID = 197, MaintenanceID = 58, Description = "Performed engine oil cooler line replacement." },
            new MaintenanceTask() { ID = 198, MaintenanceID = 23, Description = "Repaired the power steering pump bracket." },
            new MaintenanceTask() { ID = 199, MaintenanceID = 3, Description = "Checked and replaced the engine cylinder head." },
            new MaintenanceTask() { ID = 200, MaintenanceID = 83, Description = "Inspected and replaced worn ignition modules." },
            new MaintenanceTask() { ID = 201, MaintenanceID = 95, Description = "Performed engine oil filter replacement." },
            new MaintenanceTask() { ID = 202, MaintenanceID = 74, Description = "Replaced the power steering pump shaft." },
            new MaintenanceTask() { ID = 203, MaintenanceID = 79, Description = "Checked and replaced the engine serpentine belt." },
            new MaintenanceTask() { ID = 204, MaintenanceID = 57, Description = "Inspected and replaced worn spark plugs." },
            new MaintenanceTask() { ID = 205, MaintenanceID = 80, Description = "Performed engine coolant flush and refill." },
            new MaintenanceTask() { ID = 206, MaintenanceID = 61, Description = "Repaired the power steering pressure switch." },
            new MaintenanceTask() { ID = 207, MaintenanceID = 70, Description = "Checked and replaced the engine radiator." },
            new MaintenanceTask() { ID = 208, MaintenanceID = 68, Description = "Inspected and replaced worn ignition coils." },
            new MaintenanceTask() { ID = 209, MaintenanceID = 58, Description = "Performed engine air filter replacement." },
            new MaintenanceTask() { ID = 210, MaintenanceID = 63, Description = "Replaced the power steering pump pulley." },
            new MaintenanceTask() { ID = 211, MaintenanceID = 62, Description = "Checked and replaced the engine thermostat." },
            new MaintenanceTask() { ID = 212, MaintenanceID = 76, Description = "Inspected and replaced worn fuel injectors." },
            new MaintenanceTask() { ID = 213, MaintenanceID = 82, Description = "Performed engine oil drain plug replacement." },
            new MaintenanceTask() { ID = 214, MaintenanceID = 72, Description = "Repaired the power steering pressure line." },
            new MaintenanceTask() { ID = 215, MaintenanceID = 69, Description = "Checked and replaced the engine water pump." },
            new MaintenanceTask() { ID = 216, MaintenanceID = 88, Description = "Inspected and replaced worn oxygen sensor." },
            new MaintenanceTask() { ID = 217, MaintenanceID = 64, Description = "Performed engine oil cap replacement." },
            new MaintenanceTask() { ID = 218, MaintenanceID = 52, Description = "Replaced the power steering control module connector." },
            new MaintenanceTask() { ID = 219, MaintenanceID = 73, Description = "Checked and replaced the engine fuel pump." },
            new MaintenanceTask() { ID = 220, MaintenanceID = 78, Description = "Inspected and replaced worn engine mounts." },
            new MaintenanceTask() { ID = 221, MaintenanceID = 85, Description = "Performed engine oil cooler hose replacement." },
            new MaintenanceTask() { ID = 222, MaintenanceID = 77, Description = "Repaired the power steering pressure hose." },
            new MaintenanceTask() { ID = 223, MaintenanceID = 67, Description = "Checked and replaced the engine ignition control module." },
            new MaintenanceTask() { ID = 224, MaintenanceID = 66, Description = "Inspected and replaced worn engine sensors." },
            new MaintenanceTask() { ID = 225, MaintenanceID = 84, Description = "Performed engine oil pan gasket replacement." },
            new MaintenanceTask() { ID = 226, MaintenanceID = 94, Description = "Replaced the power steering reservoir." },
            new MaintenanceTask() { ID = 227, MaintenanceID = 100, Description = "Checked and replaced the engine camshaft position sensor." },
            new MaintenanceTask() { ID = 228, MaintenanceID = 92, Description = "Inspected and replaced worn drive belts." },
            new MaintenanceTask() { ID = 229, MaintenanceID = 97, Description = "Performed engine valve cover gasket replacement." },
            new MaintenanceTask() { ID = 230, MaintenanceID = 86, Description = "Repaired the power steering pump seal." },
            new MaintenanceTask() { ID = 231, MaintenanceID = 90, Description = "Checked and replaced the engine crankshaft position sensor." },
            new MaintenanceTask() { ID = 232, MaintenanceID = 98, Description = "Inspected and replaced worn timing belt." },
            new MaintenanceTask() { ID = 233, MaintenanceID = 83, Description = "Performed engine oil pressure switch replacement." },
            new MaintenanceTask() { ID = 234, MaintenanceID = 96, Description = "Replaced the power steering pressure sensor." },
            new MaintenanceTask() { ID = 235, MaintenanceID = 81, Description = "Checked and replaced the engine throttle body." },
            new MaintenanceTask() { ID = 236, MaintenanceID = 75, Description = "Inspected and replaced worn alternator." },
            new MaintenanceTask() { ID = 237, MaintenanceID = 71, Description = "Performed engine oil filter housing gasket replacement." },
            new MaintenanceTask() { ID = 238, MaintenanceID = 87, Description = "Repaired the power steering pump pulley." },
            new MaintenanceTask() { ID = 239, MaintenanceID = 99, Description = "Checked and replaced the engine oil pressure sensor." },
            new MaintenanceTask() { ID = 240, MaintenanceID = 93, Description = "Inspected and replaced worn serpentine belt tensioner." },
            new MaintenanceTask() { ID = 241, MaintenanceID = 89, Description = "Performed engine valve stem seal replacement." },
            new MaintenanceTask() { ID = 242, MaintenanceID = 91, Description = "Replaced the power steering pump reservoir." },
            new MaintenanceTask() { ID = 243, MaintenanceID = 65, Description = "Checked and replaced the engine knock sensor." },
            new MaintenanceTask() { ID = 244, MaintenanceID = 59, Description = "Inspected and replaced worn PCV valve." },
            new MaintenanceTask() { ID = 245, MaintenanceID = 60, Description = "Performed engine oil filter housing cap replacement." },
            new MaintenanceTask() { ID = 246, MaintenanceID = 55, Description = "Repaired the power steering pump bracket." },
            new MaintenanceTask() { ID = 247, MaintenanceID = 53, Description = "Checked and replaced the engine coolant temperature sensor." },
            new MaintenanceTask() { ID = 248, MaintenanceID = 56, Description = "Inspected and replaced worn intake manifold gasket." },
            new MaintenanceTask() { ID = 249, MaintenanceID = 54, Description = "Performed engine oil filler cap replacement." },
            new MaintenanceTask() { ID = 250, MaintenanceID = 51, Description = "Replaced the power steering pump o-ring." },
            new MaintenanceTask() { ID = 251, MaintenanceID = 50, Description = "Checked and replaced the engine variable valve timing solenoid." },
            new MaintenanceTask() { ID = 252, MaintenanceID = 48, Description = "Inspected and replaced worn exhaust manifold gasket." },
            new MaintenanceTask() { ID = 253, MaintenanceID = 49, Description = "Performed engine oil cooler gasket replacement." },
            new MaintenanceTask() { ID = 254, MaintenanceID = 46, Description = "Repaired the power steering pump shaft seal." },
            new MaintenanceTask() { ID = 255, MaintenanceID = 47, Description = "Checked and replaced the engine thermostat housing." },
            new MaintenanceTask() { ID = 256, MaintenanceID = 45, Description = "Inspected and replaced worn fuel pressure regulator." },
            new MaintenanceTask() { ID = 257, MaintenanceID = 43, Description = "Performed engine oil pressure relief valve replacement." },
            new MaintenanceTask() { ID = 258, MaintenanceID = 42, Description = "Replaced the power steering pump mounting bolt." },
            new MaintenanceTask() { ID = 259, MaintenanceID = 44, Description = "Checked and replaced the engine harmonic balancer." },
            new MaintenanceTask() { ID = 260, MaintenanceID = 39, Description = "Inspected and replaced worn engine timing chain." },
            new MaintenanceTask() { ID = 261, MaintenanceID = 41, Description = "Performed engine oil pump replacement." },
            new MaintenanceTask() { ID = 262, MaintenanceID = 38, Description = "Repaired the power steering pump bracket bolt." },
            new MaintenanceTask() { ID = 263, MaintenanceID = 36, Description = "Checked and replaced the engine fuel rail." },
            new MaintenanceTask() { ID = 264, MaintenanceID = 35, Description = "Inspected and replaced worn engine valve springs." },
            new MaintenanceTask() { ID = 265, MaintenanceID = 33, Description = "Performed engine oil cooler line replacement." },
            new MaintenanceTask() { ID = 266, MaintenanceID = 32, Description = "Replaced the power steering pump reservoir cap." },
            new MaintenanceTask() { ID = 267, MaintenanceID = 40, Description = "Checked and replaced the engine oil dipstick." },
            new MaintenanceTask() { ID = 268, MaintenanceID = 37, Description = "Inspected and replaced worn engine head gasket." },
            new MaintenanceTask() { ID = 269, MaintenanceID = 31, Description = "Performed engine oil filter housing seal replacement." },
            new MaintenanceTask() { ID = 270, MaintenanceID = 34, Description = "Repaired the power steering pump mounting bracket." },
            new MaintenanceTask() { ID = 271, MaintenanceID = 30, Description = "Checked and replaced the engine crankshaft seal." },
            new MaintenanceTask() { ID = 272, MaintenanceID = 29, Description = "Inspected and replaced worn engine piston rings." },
            new MaintenanceTask() { ID = 273, MaintenanceID = 28, Description = "Performed engine oil cooler thermostat replacement." },
            new MaintenanceTask() { ID = 274, MaintenanceID = 27, Description = "Replaced the power steering pump drive belt." },
            new MaintenanceTask() { ID = 275, MaintenanceID = 26, Description = "Checked and replaced the engine flywheel." },
            new MaintenanceTask() { ID = 276, MaintenanceID = 25, Description = "Inspected and replaced worn engine main bearings." },
            new MaintenanceTask() { ID = 277, MaintenanceID = 24, Description = "Performed engine oil cooler adapter replacement." },
            new MaintenanceTask() { ID = 278, MaintenanceID = 23, Description = "Repaired the power steering pump pulley bolt." },
            new MaintenanceTask() { ID = 279, MaintenanceID = 22, Description = "Checked and replaced the engine connecting rod bearings." },
            new MaintenanceTask() { ID = 280, MaintenanceID = 21, Description = "Inspected and replaced worn engine valve lifters." },
            new MaintenanceTask() { ID = 281, MaintenanceID = 20, Description = "Performed engine oil pressure gauge replacement." },
            new MaintenanceTask() { ID = 282, MaintenanceID = 19, Description = "Replaced the power steering pump pressure hose." },
            new MaintenanceTask() { ID = 283, MaintenanceID = 18, Description = "Checked and replaced the engine timing chain tensioner." },
            new MaintenanceTask() { ID = 284, MaintenanceID = 17, Description = "Inspected and replaced worn engine piston pins." },
            new MaintenanceTask() { ID = 285, MaintenanceID = 16, Description = "Performed engine oil pump drive replacement." },
            new MaintenanceTask() { ID = 286, MaintenanceID = 15, Description = "Repaired the power steering pump o-ring seal." },
            new MaintenanceTask() { ID = 287, MaintenanceID = 14, Description = "Checked and replaced the engine valve spring retainers." },
            new MaintenanceTask() { ID = 288, MaintenanceID = 13, Description = "Inspected and replaced worn engine crankshaft bearings." },
            new MaintenanceTask() { ID = 289, MaintenanceID = 12, Description = "Performed engine oil pressure relief valve spring replacement." },
            new MaintenanceTask() { ID = 290, MaintenanceID = 11, Description = "Replaced the power steering pump outlet hose." },
            new MaintenanceTask() { ID = 291, MaintenanceID = 10, Description = "Checked and replaced the engine piston rods." },
            new MaintenanceTask() { ID = 292, MaintenanceID = 9, Description = "Inspected and replaced worn engine camshaft bearings." },
            new MaintenanceTask() { ID = 293, MaintenanceID = 8, Description = "Performed engine oil pan baffle replacement." },
            new MaintenanceTask() { ID = 294, MaintenanceID = 7, Description = "Repaired the power steering pump inlet hose." },
            new MaintenanceTask() { ID = 295, MaintenanceID = 6, Description = "Checked and replaced the engine cylinder liners." },
            new MaintenanceTask() { ID = 296, MaintenanceID = 5, Description = "Inspected and replaced worn engine crankshaft." },
            new MaintenanceTask() { ID = 297, MaintenanceID = 4, Description = "Performed engine oil pump pickup tube replacement." },
            new MaintenanceTask() { ID = 298, MaintenanceID = 3, Description = "Replaced the power steering pump shaft seal." },
            new MaintenanceTask() { ID = 299, MaintenanceID = 2, Description = "Checked and replaced the engine cylinder head." },
            new MaintenanceTask() { ID = 300, MaintenanceID = 1, Description = "Inspected and replaced worn engine block." },
            new MaintenanceTask() { ID = 301, MaintenanceID = 49, Description = "Performed engine oil cooler gasket replacement." },
            new MaintenanceTask() { ID = 302, MaintenanceID = 44, Description = "Checked and replaced the engine harmonic balancer." },
            new MaintenanceTask() { ID = 303, MaintenanceID = 45, Description = "Inspected and replaced worn fuel pressure regulator." },
            new MaintenanceTask() { ID = 304, MaintenanceID = 46, Description = "Repaired the power steering pump shaft seal." },
            new MaintenanceTask() { ID = 305, MaintenanceID = 47, Description = "Checked and replaced the engine thermostat housing." },
            new MaintenanceTask() { ID = 306, MaintenanceID = 48, Description = "Replaced the engine variable valve timing solenoid." },
            new MaintenanceTask() { ID = 307, MaintenanceID = 42, Description = "Replaced the power steering pump mounting bolt." },
            new MaintenanceTask() { ID = 308, MaintenanceID = 43, Description = "Performed engine oil pressure relief valve replacement." },
            new MaintenanceTask() { ID = 309, MaintenanceID = 40, Description = "Checked and replaced the engine oil dipstick." },
            new MaintenanceTask() { ID = 310, MaintenanceID = 41, Description = "Performed engine oil pump replacement." },
            new MaintenanceTask() { ID = 311, MaintenanceID = 39, Description = "Inspected and replaced worn engine timing chain." },
            new MaintenanceTask() { ID = 312, MaintenanceID = 38, Description = "Repaired the power steering pump bracket bolt." },
            new MaintenanceTask() { ID = 313, MaintenanceID = 37, Description = "Inspected and replaced worn engine head gasket." },
            new MaintenanceTask() { ID = 314, MaintenanceID = 36, Description = "Checked and replaced the engine fuel rail." },
            new MaintenanceTask() { ID = 315, MaintenanceID = 35, Description = "Inspected and replaced worn engine valve springs." },
            new MaintenanceTask() { ID = 316, MaintenanceID = 34, Description = "Repaired the power steering pump mounting bracket." },
            new MaintenanceTask() { ID = 317, MaintenanceID = 33, Description = "Performed engine oil cooler line replacement." },
            new MaintenanceTask() { ID = 318, MaintenanceID = 32, Description = "Replaced the power steering pump reservoir cap." },
            new MaintenanceTask() { ID = 319, MaintenanceID = 31, Description = "Performed engine oil filter housing seal replacement." },
            new MaintenanceTask() { ID = 320, MaintenanceID = 30, Description = "Checked and replaced the engine crankshaft seal." },
            new MaintenanceTask() { ID = 321, MaintenanceID = 29, Description = "Inspected and replaced worn engine piston rings." },
            new MaintenanceTask() { ID = 322, MaintenanceID = 28, Description = "Performed engine oil cooler thermostat replacement." },
            new MaintenanceTask() { ID = 323, MaintenanceID = 27, Description = "Replaced the power steering pump drive belt." },
            new MaintenanceTask() { ID = 324, MaintenanceID = 26, Description = "Checked and replaced the engine flywheel." },
            new MaintenanceTask() { ID = 325, MaintenanceID = 25, Description = "Inspected and replaced worn engine main bearings." },
            new MaintenanceTask() { ID = 326, MaintenanceID = 24, Description = "Performed engine oil cooler adapter replacement." },
            new MaintenanceTask() { ID = 327, MaintenanceID = 23, Description = "Repaired the power steering pump pulley bolt." },
            new MaintenanceTask() { ID = 328, MaintenanceID = 22, Description = "Checked and replaced the engine connecting rod bearings." },
            new MaintenanceTask() { ID = 329, MaintenanceID = 21, Description = "Inspected and replaced worn engine valve lifters." },
            new MaintenanceTask() { ID = 330, MaintenanceID = 20, Description = "Performed engine oil pressure gauge replacement." },
            new MaintenanceTask() { ID = 331, MaintenanceID = 19, Description = "Replaced the power steering pump pressure hose." },
            new MaintenanceTask() { ID = 332, MaintenanceID = 18, Description = "Checked and replaced the engine timing chain tensioner." },
            new MaintenanceTask() { ID = 333, MaintenanceID = 17, Description = "Inspected and replaced worn engine piston pins." },
            new MaintenanceTask() { ID = 334, MaintenanceID = 16, Description = "Performed engine oil pump drive replacement." },
            new MaintenanceTask() { ID = 335, MaintenanceID = 15, Description = "Repaired the power steering pump o-ring seal." },
            new MaintenanceTask() { ID = 336, MaintenanceID = 14, Description = "Checked and replaced the engine valve spring retainers." },
            new MaintenanceTask() { ID = 337, MaintenanceID = 13, Description = "Inspected and replaced worn engine crankshaft bearings." },
            new MaintenanceTask() { ID = 338, MaintenanceID = 12, Description = "Performed engine oil pressure relief valve spring replacement." },
            new MaintenanceTask() { ID = 339, MaintenanceID = 11, Description = "Replaced the power steering pump outlet hose." },
            new MaintenanceTask() { ID = 340, MaintenanceID = 10, Description = "Checked and replaced the engine piston rods." },
            new MaintenanceTask() { ID = 341, MaintenanceID = 9, Description = "Inspected and replaced worn engine camshaft bearings." },
            new MaintenanceTask() { ID = 342, MaintenanceID = 8, Description = "Performed engine oil pan baffle replacement." },
            new MaintenanceTask() { ID = 343, MaintenanceID = 7, Description = "Repaired the power steering pump inlet hose." },
            new MaintenanceTask() { ID = 344, MaintenanceID = 6, Description = "Checked and replaced the engine cylinder liners." },
            new MaintenanceTask() { ID = 345, MaintenanceID = 5, Description = "Inspected and replaced worn engine crankshaft." },
            new MaintenanceTask() { ID = 346, MaintenanceID = 4, Description = "Performed engine oil pump pickup tube replacement." },
            new MaintenanceTask() { ID = 347, MaintenanceID = 3, Description = "Replaced the power steering pump shaft seal." },
            new MaintenanceTask() { ID = 348, MaintenanceID = 2, Description = "Checked and replaced the engine cylinder head." },
            new MaintenanceTask() { ID = 349, MaintenanceID = 1, Description = "Inspected and replaced worn engine block." },
            new MaintenanceTask() { ID = 350, MaintenanceID = 100, Description = "Performed engine oil cooler replacement." },
            new MaintenanceTask() { ID = 351, MaintenanceID = 99, Description = "Repaired the power steering pump mounting bracket." },
            new MaintenanceTask() { ID = 352, MaintenanceID = 98, Description = "Checked and replaced the engine valve cover gasket." },
            new MaintenanceTask() { ID = 353, MaintenanceID = 97, Description = "Inspected and replaced worn engine timing belt." },
            new MaintenanceTask() { ID = 354, MaintenanceID = 96, Description = "Performed engine oil pan replacement." },
            new MaintenanceTask() { ID = 355, MaintenanceID = 95, Description = "Replaced the power steering pump drive pulley." },
            new MaintenanceTask() { ID = 356, MaintenanceID = 94, Description = "Checked and replaced the engine intake manifold gasket." },
            new MaintenanceTask() { ID = 357, MaintenanceID = 93, Description = "Inspected and replaced worn engine valve seals." },
            new MaintenanceTask() { ID = 358, MaintenanceID = 92, Description = "Performed engine oil pump replacement." },
            new MaintenanceTask() { ID = 359, MaintenanceID = 91, Description = "Repaired the power steering pump reservoir." },
            new MaintenanceTask() { ID = 360, MaintenanceID = 90, Description = "Checked and replaced the engine exhaust manifold gasket." },
            new MaintenanceTask() { ID = 361, MaintenanceID = 89, Description = "Inspected and replaced worn engine valve lifters." },
            new MaintenanceTask() { ID = 362, MaintenanceID = 88, Description = "Performed engine oil filter housing replacement." },
            new MaintenanceTask() { ID = 363, MaintenanceID = 87, Description = "Replaced the power steering pump pressure switch." },
            new MaintenanceTask() { ID = 364, MaintenanceID = 86, Description = "Checked and replaced the engine camshaft position sensor." },
            new MaintenanceTask() { ID = 365, MaintenanceID = 85, Description = "Inspected and replaced worn engine piston rings." },
            new MaintenanceTask() { ID = 366, MaintenanceID = 84, Description = "Performed engine oil cooler line replacement." },
            new MaintenanceTask() { ID = 367, MaintenanceID = 83, Description = "Repaired the power steering pump inlet hose." },
            new MaintenanceTask() { ID = 368, MaintenanceID = 82, Description = "Checked and replaced the engine crankshaft position sensor." },
            new MaintenanceTask() { ID = 369, MaintenanceID = 81, Description = "Inspected and replaced worn engine main bearings." },
            new MaintenanceTask() { ID = 370, MaintenanceID = 80, Description = "Performed engine oil pump pickup tube replacement." },
            new MaintenanceTask() { ID = 371, MaintenanceID = 79, Description = "Replaced the power steering pump pulley bolt." },
            new MaintenanceTask() { ID = 372, MaintenanceID = 78, Description = "Checked and replaced the engine oil pressure sensor." },
            new MaintenanceTask() { ID = 373, MaintenanceID = 77, Description = "Inspected and replaced worn engine valve springs." },
            new MaintenanceTask() { ID = 374, MaintenanceID = 76, Description = "Performed engine oil cooler adapter replacement." },
            new MaintenanceTask() { ID = 375, MaintenanceID = 75, Description = "Repaired the power steering pump bracket bolt." },
            new MaintenanceTask() { ID = 376, MaintenanceID = 74, Description = "Checked and replaced the engine coolant temperature sensor." },
            new MaintenanceTask() { ID = 377, MaintenanceID = 73, Description = "Inspected and replaced worn engine piston pins." },
            new MaintenanceTask() { ID = 378, MaintenanceID = 72, Description = "Performed engine oil filter housing seal replacement." },
            new MaintenanceTask() { ID = 379, MaintenanceID = 71, Description = "Replaced the power steering pump mounting bolt." },
            new MaintenanceTask() { ID = 380, MaintenanceID = 70, Description = "Checked and replaced the engine oil pressure relief valve." },
            new MaintenanceTask() { ID = 381, MaintenanceID = 69, Description = "Inspected and replaced worn engine valve guides." },
            new MaintenanceTask() { ID = 382, MaintenanceID = 68, Description = "Performed engine oil cooler thermostat replacement." },
            new MaintenanceTask() { ID = 383, MaintenanceID = 67, Description = "Repaired the power steering pump reservoir cap." },
            new MaintenanceTask() { ID = 384, MaintenanceID = 66, Description = "Checked and replaced the engine variable valve timing solenoid." },
            new MaintenanceTask() { ID = 385, MaintenanceID = 65, Description = "Inspected and replaced worn engine piston rods." },
            new MaintenanceTask() { ID = 386, MaintenanceID = 64, Description = "Performed engine oil pump drive replacement." },
            new MaintenanceTask() { ID = 387, MaintenanceID = 63, Description = "Replaced the power steering pump pressure hose." },
            new MaintenanceTask() { ID = 388, MaintenanceID = 62, Description = "Checked and replaced the engine crankshaft seal." },
            new MaintenanceTask() { ID = 389, MaintenanceID = 61, Description = "Inspected and replaced worn engine valve lifters." },
            new MaintenanceTask() { ID = 390, MaintenanceID = 60, Description = "Performed engine oil pressure gauge replacement." },
            new MaintenanceTask() { ID = 391, MaintenanceID = 59, Description = "Repaired the power steering pump o-ring seal." },
            new MaintenanceTask() { ID = 392, MaintenanceID = 58, Description = "Checked and replaced the engine timing chain tensioner." },
            new MaintenanceTask() { ID = 393, MaintenanceID = 57, Description = "Inspected and replaced worn engine piston rings." },
            new MaintenanceTask() { ID = 394, MaintenanceID = 56, Description = "Performed engine oil cooler line replacement." },
            new MaintenanceTask() { ID = 395, MaintenanceID = 55, Description = "Replaced the power steering pump inlet hose." },
            new MaintenanceTask() { ID = 396, MaintenanceID = 54, Description = "Checked and replaced the engine flywheel." },
            new MaintenanceTask() { ID = 397, MaintenanceID = 53, Description = "Inspected and replaced worn engine main bearings." },
            new MaintenanceTask() { ID = 398, MaintenanceID = 52, Description = "Performed engine oil pump pickup tube replacement." },
            new MaintenanceTask() { ID = 399, MaintenanceID = 51, Description = "Repaired the power steering pump pulley." },
            new MaintenanceTask() { ID = 400, MaintenanceID = 50, Description = "Checked and replaced the engine connecting rod bearings." },
            new MaintenanceTask() { ID = 401, MaintenanceID = 99, Description = "Replaced the transmission fluid." },
            new MaintenanceTask() { ID = 402, MaintenanceID = 98, Description = "Inspected and replaced worn suspension bushings." },
            new MaintenanceTask() { ID = 403, MaintenanceID = 97, Description = "Performed brake fluid flush and replacement." },
            new MaintenanceTask() { ID = 404, MaintenanceID = 96, Description = "Replaced the fuel filter." },
            new MaintenanceTask() { ID = 405, MaintenanceID = 95, Description = "Checked and replaced worn spark plugs." },
            new MaintenanceTask() { ID = 406, MaintenanceID = 94, Description = "Inspected and replaced worn drive belts." },
            new MaintenanceTask() { ID = 407, MaintenanceID = 93, Description = "Performed coolant flush and replacement." },
            new MaintenanceTask() { ID = 408, MaintenanceID = 92, Description = "Replaced the air filter." },
            new MaintenanceTask() { ID = 409, MaintenanceID = 91, Description = "Checked and replaced worn wiper blades." },
            new MaintenanceTask() { ID = 410, MaintenanceID = 90, Description = "Inspected and replaced worn brake pads." },
            new MaintenanceTask() { ID = 411, MaintenanceID = 89, Description = "Performed power steering fluid flush and replacement." },
            new MaintenanceTask() { ID = 412, MaintenanceID = 88, Description = "Replaced the cabin air filter." },
            new MaintenanceTask() { ID = 413, MaintenanceID = 87, Description = "Checked and replaced worn battery." },
            new MaintenanceTask() { ID = 414, MaintenanceID = 86, Description = "Inspected and replaced worn brake rotors." },
            new MaintenanceTask() { ID = 415, MaintenanceID = 85, Description = "Performed wheel alignment and tire balancing." },
            new MaintenanceTask() { ID = 416, MaintenanceID = 84, Description = "Replaced the serpentine belt." },
            new MaintenanceTask() { ID = 417, MaintenanceID = 83, Description = "Checked and replaced worn ignition coils." },
            new MaintenanceTask() { ID = 418, MaintenanceID = 82, Description = "Inspected and replaced worn brake calipers." },
            new MaintenanceTask() { ID = 419, MaintenanceID = 81, Description = "Performed fuel system cleaning and treatment." },
            new MaintenanceTask() { ID = 420, MaintenanceID = 80, Description = "Replaced the thermostat." },
            new MaintenanceTask() { ID = 421, MaintenanceID = 79, Description = "Checked and replaced worn suspension struts." },
            new MaintenanceTask() { ID = 422, MaintenanceID = 78, Description = "Inspected and replaced worn wheel bearings." },
            new MaintenanceTask() { ID = 423, MaintenanceID = 77, Description = "Performed engine coolant temperature sensor replacement." },
            new MaintenanceTask() { ID = 424, MaintenanceID = 76, Description = "Replaced the oxygen sensor." },
            new MaintenanceTask() { ID = 425, MaintenanceID = 75, Description = "Checked and replaced worn control arm bushings." },
            new MaintenanceTask() { ID = 426, MaintenanceID = 74, Description = "Inspected and replaced worn tie rod ends." },
            new MaintenanceTask() { ID = 427, MaintenanceID = 73, Description = "Performed throttle body cleaning and service." },
            new MaintenanceTask() { ID = 428, MaintenanceID = 72, Description = "Replaced the fuel pump." },
            new MaintenanceTask() { ID = 429, MaintenanceID = 71, Description = "Checked and replaced worn ball joints." },
            new MaintenanceTask() { ID = 430, MaintenanceID = 70, Description = "Inspected and replaced worn sway bar links." },
            new MaintenanceTask() { ID = 431, MaintenanceID = 69, Description = "Performed transmission filter replacement." },
            new MaintenanceTask() { ID = 432, MaintenanceID = 68, Description = "Replaced the PCV valve." },
            new MaintenanceTask() { ID = 433, MaintenanceID = 67, Description = "Checked and replaced worn drive shafts." },
            new MaintenanceTask() { ID = 434, MaintenanceID = 66, Description = "Inspected and replaced worn wheel hubs." },
            new MaintenanceTask() { ID = 435, MaintenanceID = 65, Description = "Performed engine air intake cleaning and service." },
            new MaintenanceTask() { ID = 436, MaintenanceID = 64, Description = "Replaced the mass air flow sensor." },
            new MaintenanceTask() { ID = 437, MaintenanceID = 63, Description = "Checked and replaced worn CV joints." },
            new MaintenanceTask() { ID = 438, MaintenanceID = 62, Description = "Inspected and replaced worn shock absorbers." },
            new MaintenanceTask() { ID = 439, MaintenanceID = 61, Description = "Performed brake caliper rebuild and service." },
            new MaintenanceTask() { ID = 440, MaintenanceID = 60, Description = "Replaced the radiator." },
            new MaintenanceTask() { ID = 441, MaintenanceID = 59, Description = "Checked and replaced worn wheel studs." },
            new MaintenanceTask() { ID = 442, MaintenanceID = 58, Description = "Inspected and replaced worn exhaust system components." },
            new MaintenanceTask() { ID = 443, MaintenanceID = 57, Description = "Performed engine valve adjustment." },
            new MaintenanceTask() { ID = 444, MaintenanceID = 56, Description = "Replaced the alternator." },
            new MaintenanceTask() { ID = 445, MaintenanceID = 55, Description = "Checked and replaced worn drive belts tensioner." },
            new MaintenanceTask() { ID = 446, MaintenanceID = 54, Description = "Inspected and replaced worn fuel injectors." },
            new MaintenanceTask() { ID = 447, MaintenanceID = 53, Description = "Performed power steering rack and pinion replacement." },
            new MaintenanceTask() { ID = 448, MaintenanceID = 52, Description = "Replaced the timing belt." },
            new MaintenanceTask() { ID = 449, MaintenanceID = 51, Description = "Checked and replaced worn engine mounts." },
            new MaintenanceTask() { ID = 450, MaintenanceID = 50, Description = "Inspected and replaced worn brake hoses." },
            new MaintenanceTask() { ID = 451, MaintenanceID = 50, Description = "Performed wheel bearing replacement." },
            new MaintenanceTask() { ID = 452, MaintenanceID = 49, Description = "Replaced the radiator hose." },
            new MaintenanceTask() { ID = 453, MaintenanceID = 48, Description = "Checked and replaced worn timing chain." },
            new MaintenanceTask() { ID = 454, MaintenanceID = 47, Description = "Inspected and replaced worn camshaft position sensor." },
            new MaintenanceTask() { ID = 455, MaintenanceID = 46, Description = "Performed brake master cylinder replacement." },
            new MaintenanceTask() { ID = 456, MaintenanceID = 45, Description = "Replaced the throttle position sensor." },
            new MaintenanceTask() { ID = 457, MaintenanceID = 44, Description = "Checked and replaced worn transmission mount." },
            new MaintenanceTask() { ID = 458, MaintenanceID = 43, Description = "Inspected and replaced worn engine control module (ECM)." },
            new MaintenanceTask() { ID = 459, MaintenanceID = 42, Description = "Performed differential fluid flush and replacement." },
            new MaintenanceTask() { ID = 460, MaintenanceID = 41, Description = "Replaced the power steering pump." },
            new MaintenanceTask() { ID = 461, MaintenanceID = 40, Description = "Checked and replaced worn fuel pressure regulator." },
            new MaintenanceTask() { ID = 462, MaintenanceID = 39, Description = "Inspected and replaced worn ignition switch." },
            new MaintenanceTask() { ID = 463, MaintenanceID = 38, Description = "Performed brake booster replacement." },
            new MaintenanceTask() { ID = 464, MaintenanceID = 37, Description = "Replaced the engine mount." },
            new MaintenanceTask() { ID = 465, MaintenanceID = 36, Description = "Checked and replaced worn exhaust manifold gasket." },
            new MaintenanceTask() { ID = 466, MaintenanceID = 35, Description = "Inspected and replaced worn intake manifold gasket." },
            new MaintenanceTask() { ID = 467, MaintenanceID = 34, Description = "Performed fuel injector cleaning and service." },
            new MaintenanceTask() { ID = 468, MaintenanceID = 33, Description = "Replaced the drive shaft." },
            new MaintenanceTask() { ID = 469, MaintenanceID = 32, Description = "Checked and replaced worn fuel tank." },
            new MaintenanceTask() { ID = 470, MaintenanceID = 31, Description = "Inspected and replaced worn steering gear box." },
            new MaintenanceTask() { ID = 471, MaintenanceID = 30, Description = "Performed thermostat housing replacement." },
            new MaintenanceTask() { ID = 472, MaintenanceID = 29, Description = "Replaced the ignition coil pack." },
            new MaintenanceTask() { ID = 473, MaintenanceID = 28, Description = "Checked and replaced worn valve cover gasket." },
            new MaintenanceTask() { ID = 474, MaintenanceID = 27, Description = "Inspected and replaced worn drive belt tensioner." },
            new MaintenanceTask() { ID = 475, MaintenanceID = 26, Description = "Performed brake proportioning valve replacement." },
            new MaintenanceTask() { ID = 476, MaintenanceID = 25, Description = "Replaced the oxygen sensor." },
            new MaintenanceTask() { ID = 477, MaintenanceID = 24, Description = "Checked and replaced worn serpentine belt." },
            new MaintenanceTask() { ID = 478, MaintenanceID = 23, Description = "Inspected and replaced worn water pump." },
            new MaintenanceTask() { ID = 479, MaintenanceID = 22, Description = "Performed throttle body sensor replacement." },
            new MaintenanceTask() { ID = 480, MaintenanceID = 21, Description = "Replaced the brake caliper." },
            new MaintenanceTask() { ID = 481, MaintenanceID = 20, Description = "Checked and replaced worn spark plugs." },
            new MaintenanceTask() { ID = 482, MaintenanceID = 19, Description = "Inspected and replaced worn fuel filter." },
            new MaintenanceTask() { ID = 483, MaintenanceID = 18, Description = "Performed shock absorber replacement." },
            new MaintenanceTask() { ID = 484, MaintenanceID = 17, Description = "Replaced the transmission mount." },
            new MaintenanceTask() { ID = 485, MaintenanceID = 16, Description = "Checked and replaced worn throttle body." },
            new MaintenanceTask() { ID = 486, MaintenanceID = 15, Description = "Inspected and replaced worn ignition module." },
            new MaintenanceTask() { ID = 487, MaintenanceID = 14, Description = "Performed fuel pump relay replacement." },
            new MaintenanceTask() { ID = 488, MaintenanceID = 13, Description = "Replaced the starter motor." },
            new MaintenanceTask() { ID = 489, MaintenanceID = 12, Description = "Checked and replaced worn brake pads." },
            new MaintenanceTask() { ID = 490, MaintenanceID = 11, Description = "Inspected and replaced worn radiator fan." },
            new MaintenanceTask() { ID = 491, MaintenanceID = 10, Description = "Performed alternator belt replacement." },
            new MaintenanceTask() { ID = 492, MaintenanceID = 9, Description = "Replaced the camshaft position sensor." },
            new MaintenanceTask() { ID = 493, MaintenanceID = 8, Description = "Checked and replaced worn power steering hose." },
            new MaintenanceTask() { ID = 494, MaintenanceID = 7, Description = "Inspected and replaced worn wheel bearing hub assembly." },
            new MaintenanceTask() { ID = 495, MaintenanceID = 6, Description = "Performed EGR valve replacement." },
            new MaintenanceTask() { ID = 496, MaintenanceID = 5, Description = "Replaced the thermostat." },
            new MaintenanceTask() { ID = 497, MaintenanceID = 4, Description = "Checked and replaced worn ignition spark plug wires." },
            new MaintenanceTask() { ID = 498, MaintenanceID = 3, Description = "Inspected and replaced worn fuel pressure sensor." },
            new MaintenanceTask() { ID = 499, MaintenanceID = 2, Description = "Performed brake fluid flush and replacement." },
            new MaintenanceTask() { ID = 500, MaintenanceID = 1, Description = "Replaced the serpentine belt tensioner." }
        );
    }
}