using FleetManager.EntityFrameworkDAL.Models.Entities;
using Microsoft.EntityFrameworkCore;

namespace FleetManager.EntityFrameworkDAL.Context.Seeding.TestSeeding;
public static class VehiclePartTestSeed {
    public static void TestSeedVehiclePart(this ModelBuilder modelBuilder) {
        modelBuilder.Entity<VehiclePart>().HasData(
            new VehiclePart() { ID = 1, Name = "Remblok" },
            new VehiclePart() { ID = 2, Name = "Bougie" },
            new VehiclePart() { ID = 3, Name = "Batterij" },
            new VehiclePart() { ID = 4, Name = "Oliefilter" },
            new VehiclePart() { ID = 5, Name = "Luchtfilter" },
            new VehiclePart() { ID = 6, Name = "Dynamo" },
            new VehiclePart() { ID = 7, Name = "Radiateur" },
            new VehiclePart() { ID = 8, Name = "Startmotor" },
            new VehiclePart() { ID = 9, Name = "Brandstofpomp" },
            new VehiclePart() { ID = 10, Name = "Ontstekingsspoel" },
            new VehiclePart() { ID = 11, Name = "Band" },
            new VehiclePart() { ID = 12, Name = "Ophangingsbus" },
            new VehiclePart() { ID = 13, Name = "Remschijf" },
            new VehiclePart() { ID = 14, Name = "Waterpomp" },
            new VehiclePart() { ID = 15, Name = "Distributieriem" },
            new VehiclePart() { ID = 16, Name = "Thermostaat" },
            new VehiclePart() { ID = 17, Name = "Draagarm" },
            new VehiclePart() { ID = 18, Name = "Stuurhuis" },
            new VehiclePart() { ID = 19, Name = "Wielnaaf" },
            new VehiclePart() { ID = 20, Name = "Homokineet" },
            new VehiclePart() { ID = 21, Name = "Krukas" },
            new VehiclePart() { ID = 22, Name = "Nokkenas" },
            new VehiclePart() { ID = 23, Name = "Kleppendeksel" },
            new VehiclePart() { ID = 24, Name = "Uitlaatspruitstuk" },
            new VehiclePart() { ID = 25, Name = "Katalysator" },
            new VehiclePart() { ID = 26, Name = "Lambda-sensor" },
            new VehiclePart() { ID = 27, Name = "Stuurbekrachtigingspomp" },
            new VehiclePart() { ID = 28, Name = "Brandstofinjector" },
            new VehiclePart() { ID = 29, Name = "Airconditioningcompressor" },
            new VehiclePart() { ID = 30, Name = "Blowermotor" },
            new VehiclePart() { ID = 31, Name = "Deurvergrendelingsmotor" },
            new VehiclePart() { ID = 32, Name = "Raammechanisme" },
            new VehiclePart() { ID = 33, Name = "Brandstoftank" },
            new VehiclePart() { ID = 34, Name = "EGR-klep" },
            new VehiclePart() { ID = 35, Name = "Luchtmassameter" },
            new VehiclePart() { ID = 36, Name = "Ontstekingsschakelaar" },
            new VehiclePart() { ID = 37, Name = "Versnellingsbaksteun" },
            new VehiclePart() { ID = 38, Name = "Motorsteun" },
            new VehiclePart() { ID = 39, Name = "Multiriem" },
            new VehiclePart() { ID = 40, Name = "Spanrol" },
            new VehiclePart() { ID = 41, Name = "Wiellager" },
            new VehiclePart() { ID = 42, Name = "Remklauw" },
            new VehiclePart() { ID = 43, Name = "Hoofdremcilinder" },
            new VehiclePart() { ID = 44, Name = "Brandstoffilter" },
            new VehiclePart() { ID = 45, Name = "Koplampunit" },
            new VehiclePart() { ID = 46, Name = "Achterlicht" },
            new VehiclePart() { ID = 47, Name = "Buitenspiegel" },
            new VehiclePart() { ID = 48, Name = "Voorspatbord" },
            new VehiclePart() { ID = 49, Name = "Grille" },
            new VehiclePart() { ID = 50, Name = "Radiateurventilator" },
            new VehiclePart() { ID = 51, Name = "Gasklephuis" },
            new VehiclePart() { ID = 52, Name = "Inlaatspruitstuk" },
            new VehiclePart() { ID = 53, Name = "Elektrisch raambediening" },
            new VehiclePart() { ID = 54, Name = "Cruise control module" },
            new VehiclePart() { ID = 55, Name = "Weerstand blowermotor" },
            new VehiclePart() { ID = 56, Name = "ABS-regelmodule" },
            new VehiclePart() { ID = 57, Name = "Stuurwiel" },
            new VehiclePart() { ID = 58, Name = "Veiligheidsgordel" },
            new VehiclePart() { ID = 59, Name = "Schuifdakmotor" },
            new VehiclePart() { ID = 60, Name = "Airconditioningcondensor" },
            new VehiclePart() { ID = 61, Name = "Uitlaatpijp" },
            new VehiclePart() { ID = 62, Name = "Ontsturingsmodule" },
            new VehiclePart() { ID = 63, Name = "Gaskleppositiesensor" },
            new VehiclePart() { ID = 64, Name = "Brandstofdrukregelaar" },
            new VehiclePart() { ID = 65, Name = "Cabineluchtfilter" },
            new VehiclePart() { ID = 66, Name = "Transmissiefilter" },
            new VehiclePart() { ID = 67, Name = "Wielmoer" },
            new VehiclePart() { ID = 68, Name = "Schokdemper" },
            new VehiclePart() { ID = 69, Name = "Veerpoot" },
            new VehiclePart() { ID = 70, Name = "Stuurkolom" },
            new VehiclePart() { ID = 71, Name = "Aandrijfas" },
            new VehiclePart() { ID = 72, Name = "Contactslot" },
            new VehiclePart() { ID = 73, Name = "Krukaspositiesensor" },
            new VehiclePart() { ID = 74, Name = "Nokkenaspositiesensor" },
            new VehiclePart() { ID = 75, Name = "Stuurbekrachtigingsslang" },
            new VehiclePart() { ID = 76, Name = "Brandstofvulhals" },
            new VehiclePart() { ID = 77, Name = "Raammotor" },
            new VehiclePart() { ID = 78, Name = "Uitlaatpakking" },
            new VehiclePart() { ID = 79, Name = "Stuurknokkel" },
            new VehiclePart() { ID = 80, Name = "Aslager" },
            new VehiclePart() { ID = 81, Name = "Verdeelkap" },
            new VehiclePart() { ID = 82, Name = "Ontstekingsrotor" },
            new VehiclePart() { ID = 83, Name = "Koplamplamp" },
            new VehiclePart() { ID = 84, Name = "Knipperlichtschakelaar" },
            new VehiclePart() { ID = 85, Name = "Ruitenwisserblad" },
            new VehiclePart() { ID = 86, Name = "Brandstoftankdop" },
            new VehiclePart() { ID = 87, Name = "Startersolenoïde" },
            new VehiclePart() { ID = 88, Name = "Elektrische deurvergrendelingsactuator" },
            new VehiclePart() { ID = 89, Name = "EGR-buis" },
            new VehiclePart() { ID = 90, Name = "Brandstofdruksensor" },
            new VehiclePart() { ID = 91, Name = "Cilinderkop" },
            new VehiclePart() { ID = 92, Name = "Zuigerveer" },
            new VehiclePart() { ID = 93, Name = "Hoofdlagerset" },
            new VehiclePart() { ID = 94, Name = "Drijfstang" },
            new VehiclePart() { ID = 95, Name = "Motorpakkingset" },
            new VehiclePart() { ID = 96, Name = "Motorsteun" },
            new VehiclePart() { ID = 97, Name = "Distributieketting" },
            new VehiclePart() { ID = 98, Name = "Brandstofniveausensor" },
            new VehiclePart() { ID = 99, Name = "Stabilisatorstangkoppeling" },
            new VehiclePart() { ID = 100, Name = "Transmissiebesturingsmodule" }
        );
    }
}